### ISSUE TITLE
ModuleNotFoundError: No module named 'zksync_sdk.types'

### ISSUE THREAD

**Issue by yumen** [zksync-sdk/zksync-python#2]
from zksync_sdk import HttpJsonRPCTransport, ZkSyncProviderV01, network
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/py38/lib/python3.8/site-packages/zksync_sdk/__init__.py", line 1, in <module>
    from .ethereum_provider import EthereumProvider
  File "/home/ubuntu/anaconda3/envs/py38/lib/python3.8/site-packages/zksync_sdk/ethereum_provider.py", line 5, in <module>
    from zksync_sdk.types import Token
ModuleNotFoundError: No module named 'zksync_sdk.types'

**Comment by popzxc** [comment]
@Deniallugo please look into this

**Comment by Deniallugo** [comment]
It was a problem with installing the library. I fixed it.

**Comment by StanislavBreadless** [comment]
@yumen I'm closing the issue as it is solved. If the problem persists, feel free to reopen :slightly_smiling_face:
